name: CI SCAN
on: push
jobs:
  semgrep-sast:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
  
    steps:
      - name: clone repo
        uses: actions/checkout@v4
    
      - name: Semgrep SAST Scan
        run:  |
          semgrep \
            --sarif --output report.sarif \
            --metrics=off \
            --config="p/default"

      - name: upload report to artifact
        uses: actions/upload-artifact@v3
        with:
          name: report.sarif
          path: report.sarif
      
      - name: Intialize CODE QL
        uses: github/codeql-actions/init@v3
      - name: Autobuild
        uses: github/codeql-actions/autobuild@v3
        with:
          language: ${{ matrix.language}}
      - name: Analyze
        uses: github/codeql-actions/analyze@v3
