name: CI SCAN
on: push
jobs:
  Semgrep SAST Scanning
    runs-on: ubunut-latest
    container:
      image: returntocorp/semgrep
  
    steps:
      - name: clone repo
        uses: actions/checkout@v4
    
      - name: Semgrep SAST Scan
        run:  |
          semgrep \
            --sarif --output report.sarif \
            --metrics=off \
            --config="p/default"

      - name: upload report to artifact
        uses: actions/upload-artifact@v3
        with:
          name: report.sarif
          path: report.sarif